AWSTemplateFormatVersion: '2010-09-09'
Description: Template to deploy the Lambda layer and functions for Kafka Admin Resources
Transform:
  - AWS::Serverless-2016-10-31
Metadata:
  Maintainer: john@compose-x.io
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Parameters:
          - LayerName
        Label:
          default: Lambda Layer Configuration

Parameters:
  LayerName:
    Type: String
    Default: cfn-kafka-admin
    Description: Name of the Lambda layer
  PublishLayer:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    Description: Publish the layer to public
Conditions:
  PublishLayerCon: !Equals [!Ref PublishLayer, "true"]
Resources:
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    RetentionPolicy: Retain
    Properties:
      CompatibleRuntimes:
        - python3.10
      ContentUri: ${S3_LAYER_UPLOAD_PATH}
      Description: Kafka resources library for AWS CFN
      LayerName:
        Ref: LayerName
      LicenseInfo: MPL-2.0

  LambdaLayerPermission:
    Condition: PublishLayerCon
    Type: AWS::Lambda::LayerVersionPermission
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      LayerVersionArn: !Ref LambdaLayer
      Action: lambda:GetLayerVersion
      Principal: "*"

Outputs:
  LayerArn:
    Value:
      Ref: LambdaLayer
